import type { Metadata } from "next";
import { Inter } from "next/font/google"
import "./globals.css";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";

const inter = Inter({
  subsets:['latin'],
  weight: [ '200', '400','500', '600', '700']
})

export const metadata: Metadata = {
  title: "Grupo suçuarana",
  description: "Generated by Luis J13",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
